services:
  sveltekit-app:
    build: ./frontend
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - sveltekit-app
  backend:
    build: ./backend
    ports:
      - "8000:8000"